namespace QuanLyKhachSan.Forms
{
    partial class FrmDanhMuc
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.tabCtrl = new System.Windows.Forms.TabControl();
            this.tabKhu = new System.Windows.Forms.TabPage();
            this.dgvKhu = new System.Windows.Forms.DataGridView();
            this.btnThemKhu = new System.Windows.Forms.Button();
            this.txtKhuTen = new System.Windows.Forms.TextBox();
            this.lblKhuTen = new System.Windows.Forms.Label();
            this.txtKhuMa = new System.Windows.Forms.TextBox();
            this.lblKhuMa = new System.Windows.Forms.Label();
            this.tabNV = new System.Windows.Forms.TabPage();
            this.dgvNV = new System.Windows.Forms.DataGridView();
            this.btnThemNV = new System.Windows.Forms.Button();
            this.txtNVSDT = new System.Windows.Forms.TextBox();
            this.lblNVSDT = new System.Windows.Forms.Label();
            this.txtNVVaiTro = new System.Windows.Forms.TextBox();
            this.lblNVVaiTro = new System.Windows.Forms.Label();
            this.txtNVTen = new System.Windows.Forms.TextBox();
            this.lblNVTen = new System.Windows.Forms.Label();
            this.txtNVMa = new System.Windows.Forms.TextBox();
            this.lblNVMa = new System.Windows.Forms.Label();
            this.tabLoai = new System.Windows.Forms.TabPage();
            this.dgvLoaiTN = new System.Windows.Forms.DataGridView();
            this.btnThemLoaiTN = new System.Windows.Forms.Button();
            this.txtLoaiTen = new System.Windows.Forms.TextBox();
            this.lblLoaiTen = new System.Windows.Forms.Label();
            this.txtLoaiMa = new System.Windows.Forms.TextBox();
            this.lblLoaiMa = new System.Windows.Forms.Label();
            this.tabDV = new System.Windows.Forms.TabPage();
            this.dgvDV = new System.Windows.Forms.DataGridView();
            this.btnThemDV = new System.Windows.Forms.Button();
            this.numDVGia = new System.Windows.Forms.NumericUpDown();
            this.lblDVGia = new System.Windows.Forms.Label();
            this.txtDVDVT = new System.Windows.Forms.TextBox();
            this.lblDVDVT = new System.Windows.Forms.Label();
            this.txtDVTen = new System.Windows.Forms.TextBox();
            this.lblDVTen = new System.Windows.Forms.Label();
            this.txtDVMa = new System.Windows.Forms.TextBox();
            this.lblDVMa = new System.Windows.Forms.Label();
            this.tabQD = new System.Windows.Forms.TabPage();
            this.dgvQD = new System.Windows.Forms.DataGridView();
            this.btnThemQD = new System.Windows.Forms.Button();
            this.numQDTien = new System.Windows.Forms.NumericUpDown();
            this.lblQDTien = new System.Windows.Forms.Label();
            this.txtQDMucDo = new System.Windows.Forms.TextBox();
            this.lblQDMucDo = new System.Windows.Forms.Label();
            this.cboQDLoai = new System.Windows.Forms.ComboBox();
            this.lblQDLoai = new System.Windows.Forms.Label();
            this.txtQDMa = new System.Windows.Forms.TextBox();
            this.lblQDMa = new System.Windows.Forms.Label();
            this.tabCtrl.SuspendLayout();
            this.tabKhu.SuspendLayout();
            this.tabNV.SuspendLayout();
            this.tabLoai.SuspendLayout();
            this.tabDV.SuspendLayout();
            this.tabQD.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhu)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNV)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLoaiTN)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDV)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDVGia)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvQD)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numQDTien)).BeginInit();
            this.SuspendLayout();
            // tabCtrl
            this.tabCtrl.Controls.Add(this.tabKhu);
            this.tabCtrl.Controls.Add(this.tabNV);
            this.tabCtrl.Controls.Add(this.tabLoai);
            this.tabCtrl.Controls.Add(this.tabDV);
            this.tabCtrl.Controls.Add(this.tabQD);
            this.tabCtrl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabCtrl.Location = new System.Drawing.Point(0, 0);
            this.tabCtrl.Name = "tabCtrl";
            this.tabCtrl.Size = new System.Drawing.Size(784, 461);
            // Tab Khu
            this.tabKhu.Controls.Add(this.dgvKhu);
            this.tabKhu.Controls.Add(this.btnThemKhu);
            this.tabKhu.Controls.Add(this.txtKhuTen);
            this.tabKhu.Controls.Add(this.lblKhuTen);
            this.tabKhu.Controls.Add(this.txtKhuMa);
            this.tabKhu.Controls.Add(this.lblKhuMa);
            this.tabKhu.Text = "Khu vực";
            this.lblKhuMa.Location = new System.Drawing.Point(15, 18);
            this.lblKhuMa.Size = new System.Drawing.Size(35, 20);
            this.lblKhuMa.Text = "Mã:";
            this.txtKhuMa.Location = new System.Drawing.Point(55, 15);
            this.txtKhuMa.Size = new System.Drawing.Size(120, 22);
            this.lblKhuTen.Location = new System.Drawing.Point(195, 18);
            this.lblKhuTen.Size = new System.Drawing.Size(35, 20);
            this.lblKhuTen.Text = "Tên:";
            this.txtKhuTen.Location = new System.Drawing.Point(235, 15);
            this.txtKhuTen.Size = new System.Drawing.Size(200, 22);
            this.btnThemKhu.Location = new System.Drawing.Point(460, 12);
            this.btnThemKhu.Size = new System.Drawing.Size(90, 28);
            this.btnThemKhu.Text = "Thêm";
            this.btnThemKhu.Click += new System.EventHandler(this.btnThemKhu_Click);
            this.dgvKhu.Location = new System.Drawing.Point(15, 55);
            this.dgvKhu.Size = new System.Drawing.Size(745, 365);
            // Tab NV
            this.tabNV.Controls.Add(this.dgvNV);
            this.tabNV.Controls.Add(this.btnThemNV);
            this.tabNV.Controls.Add(this.txtNVSDT);
            this.tabNV.Controls.Add(this.lblNVSDT);
            this.tabNV.Controls.Add(this.txtNVVaiTro);
            this.tabNV.Controls.Add(this.lblNVVaiTro);
            this.tabNV.Controls.Add(this.txtNVTen);
            this.tabNV.Controls.Add(this.lblNVTen);
            this.tabNV.Controls.Add(this.txtNVMa);
            this.tabNV.Controls.Add(this.lblNVMa);
            this.tabNV.Text = "Nhân viên";
            this.lblNVMa.Location = new System.Drawing.Point(10, 18);
            this.lblNVMa.Size = new System.Drawing.Size(30, 20);
            this.lblNVMa.Text = "Mã:";
            this.txtNVMa.Location = new System.Drawing.Point(45, 15);
            this.txtNVMa.Size = new System.Drawing.Size(80, 22);
            this.lblNVTen.Location = new System.Drawing.Point(135, 18);
            this.lblNVTen.Size = new System.Drawing.Size(35, 20);
            this.lblNVTen.Text = "Tên:";
            this.txtNVTen.Location = new System.Drawing.Point(175, 15);
            this.txtNVTen.Size = new System.Drawing.Size(140, 22);
            this.lblNVVaiTro.Location = new System.Drawing.Point(325, 18);
            this.lblNVVaiTro.Size = new System.Drawing.Size(50, 20);
            this.lblNVVaiTro.Text = "Vai trò:";
            this.txtNVVaiTro.Location = new System.Drawing.Point(380, 15);
            this.txtNVVaiTro.Size = new System.Drawing.Size(100, 22);
            this.lblNVSDT.Location = new System.Drawing.Point(490, 18);
            this.lblNVSDT.Size = new System.Drawing.Size(40, 20);
            this.lblNVSDT.Text = "SĐT:";
            this.txtNVSDT.Location = new System.Drawing.Point(535, 15);
            this.txtNVSDT.Size = new System.Drawing.Size(100, 22);
            this.btnThemNV.Location = new System.Drawing.Point(655, 12);
            this.btnThemNV.Size = new System.Drawing.Size(85, 28);
            this.btnThemNV.Text = "Thêm";
            this.btnThemNV.Click += new System.EventHandler(this.btnThemNV_Click);
            this.dgvNV.Location = new System.Drawing.Point(15, 55);
            this.dgvNV.Size = new System.Drawing.Size(745, 365);
            // Tab Loai
            this.tabLoai.Controls.Add(this.dgvLoaiTN);
            this.tabLoai.Controls.Add(this.btnThemLoaiTN);
            this.tabLoai.Controls.Add(this.txtLoaiTen);
            this.tabLoai.Controls.Add(this.lblLoaiTen);
            this.tabLoai.Controls.Add(this.txtLoaiMa);
            this.tabLoai.Controls.Add(this.lblLoaiMa);
            this.tabLoai.Text = "Loại tiện nghi";
            this.lblLoaiMa.Location = new System.Drawing.Point(15, 18);
            this.lblLoaiMa.Size = new System.Drawing.Size(35, 20);
            this.lblLoaiMa.Text = "Mã:";
            this.txtLoaiMa.Location = new System.Drawing.Point(55, 15);
            this.txtLoaiMa.Size = new System.Drawing.Size(120, 22);
            this.lblLoaiTen.Location = new System.Drawing.Point(195, 18);
            this.lblLoaiTen.Size = new System.Drawing.Size(35, 20);
            this.lblLoaiTen.Text = "Tên:";
            this.txtLoaiTen.Location = new System.Drawing.Point(235, 15);
            this.txtLoaiTen.Size = new System.Drawing.Size(200, 22);
            this.btnThemLoaiTN.Location = new System.Drawing.Point(460, 12);
            this.btnThemLoaiTN.Size = new System.Drawing.Size(90, 28);
            this.btnThemLoaiTN.Text = "Thêm";
            this.btnThemLoaiTN.Click += new System.EventHandler(this.btnThemLoaiTN_Click);
            this.dgvLoaiTN.Location = new System.Drawing.Point(15, 55);
            this.dgvLoaiTN.Size = new System.Drawing.Size(745, 365);
            // Tab Dich Vu (Theo y chang Hình 2 của bài Lab)
            this.tabDV.Controls.Add(this.dgvDV);
            this.tabDV.Controls.Add(this.btnThemDV);
            this.tabDV.Controls.Add(this.numDVGia);
            this.tabDV.Controls.Add(this.lblDVGia);
            this.tabDV.Controls.Add(this.txtDVDVT);
            this.tabDV.Controls.Add(this.lblDVDVT);
            this.tabDV.Controls.Add(this.txtDVTen);
            this.tabDV.Controls.Add(this.lblDVTen);
            this.tabDV.Controls.Add(this.txtDVMa);
            this.tabDV.Controls.Add(this.lblDVMa);
            this.tabDV.Text = "Dịch vụ";
            this.lblDVMa.Location = new System.Drawing.Point(15, 18);
            this.lblDVMa.Size = new System.Drawing.Size(30, 20);
            this.lblDVMa.Text = "Mã:";
            this.txtDVMa.Location = new System.Drawing.Point(50, 15);
            this.txtDVMa.Size = new System.Drawing.Size(80, 22);
            this.lblDVTen.Location = new System.Drawing.Point(140, 18);
            this.lblDVTen.Size = new System.Drawing.Size(35, 20);
            this.lblDVTen.Text = "Tên:";
            this.txtDVTen.Location = new System.Drawing.Point(180, 15);
            this.txtDVTen.Size = new System.Drawing.Size(130, 22);
            this.lblDVDVT.Location = new System.Drawing.Point(320, 18);
            this.lblDVDVT.Size = new System.Drawing.Size(75, 20);
            this.lblDVDVT.Text = "Đơn vị / Vai trò:";
            this.txtDVDVT.Location = new System.Drawing.Point(400, 15);
            this.txtDVDVT.Size = new System.Drawing.Size(85, 22);
            this.lblDVGia.Location = new System.Drawing.Point(495, 18);
            this.lblDVGia.Size = new System.Drawing.Size(55, 20);
            this.lblDVGia.Text = "Đơn giá:";
            this.numDVGia.Location = new System.Drawing.Point(555, 15);
            this.numDVGia.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numDVGia.Size = new System.Drawing.Size(100, 22);
            this.btnThemDV.Location = new System.Drawing.Point(670, 12);
            this.btnThemDV.Size = new System.Drawing.Size(80, 28);
            this.btnThemDV.Text = "Thêm";
            this.btnThemDV.Click += new System.EventHandler(this.btnThemDV_Click);
            this.dgvDV.Location = new System.Drawing.Point(15, 55);
            this.dgvDV.Size = new System.Drawing.Size(745, 365);
            // Tab Quy Dinh
            this.tabQD.Controls.Add(this.dgvQD);
            this.tabQD.Controls.Add(this.btnThemQD);
            this.tabQD.Controls.Add(this.numQDTien);
            this.tabQD.Controls.Add(this.lblQDTien);
            this.tabQD.Controls.Add(this.txtQDMucDo);
            this.tabQD.Controls.Add(this.lblQDMucDo);
            this.tabQD.Controls.Add(this.cboQDLoai);
            this.tabQD.Controls.Add(this.lblQDLoai);
            this.tabQD.Controls.Add(this.txtQDMa);
            this.tabQD.Controls.Add(this.lblQDMa);
            this.tabQD.Text = "Quy định đền bù";
            this.lblQDMa.Location = new System.Drawing.Point(10, 18);
            this.lblQDMa.Size = new System.Drawing.Size(30, 20);
            this.lblQDMa.Text = "Mã:";
            this.txtQDMa.Location = new System.Drawing.Point(45, 15);
            this.txtQDMa.Size = new System.Drawing.Size(70, 22);
            this.lblQDLoai.Location = new System.Drawing.Point(125, 18);
            this.lblQDLoai.Size = new System.Drawing.Size(55, 20);
            this.lblQDLoai.Text = "Loại TN:";
            this.cboQDLoai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboQDLoai.Location = new System.Drawing.Point(185, 15);
            this.cboQDLoai.Size = new System.Drawing.Size(110, 24);
            this.lblQDMucDo.Location = new System.Drawing.Point(305, 18);
            this.lblQDMucDo.Size = new System.Drawing.Size(55, 20);
            this.lblQDMucDo.Text = "Mức độ:";
            this.txtQDMucDo.Location = new System.Drawing.Point(365, 15);
            this.txtQDMucDo.Size = new System.Drawing.Size(120, 22);
            this.lblQDTien.Location = new System.Drawing.Point(495, 18);
            this.lblQDTien.Size = new System.Drawing.Size(50, 20);
            this.lblQDTien.Text = "Số tiền:";
            this.numQDTien.Location = new System.Drawing.Point(550, 15);
            this.numQDTien.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numQDTien.Size = new System.Drawing.Size(100, 22);
            this.btnThemQD.Location = new System.Drawing.Point(665, 12);
            this.btnThemQD.Size = new System.Drawing.Size(85, 28);
            this.btnThemQD.Text = "Thêm";
            this.btnThemQD.Click += new System.EventHandler(this.btnThemQD_Click);
            this.dgvQD.Location = new System.Drawing.Point(15, 55);
            this.dgvQD.Size = new System.Drawing.Size(745, 365);
            // FrmDanhMuc
            this.ClientSize = new System.Drawing.Size(784, 461);
            this.Controls.Add(this.tabCtrl);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Danh mục khách sạn";
            this.Load += new System.EventHandler(this.FrmDanhMuc_Load);
            this.tabCtrl.ResumeLayout(false);
            this.tabKhu.ResumeLayout(false);
            this.tabKhu.PerformLayout();
            this.tabNV.ResumeLayout(false);
            this.tabNV.PerformLayout();
            this.tabLoai.ResumeLayout(false);
            this.tabLoai.PerformLayout();
            this.tabDV.ResumeLayout(false);
            this.tabDV.PerformLayout();
            this.tabQD.ResumeLayout(false);
            this.tabQD.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhu)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNV)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLoaiTN)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDV)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDVGia)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvQD)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numQDTien)).EndInit();
            this.ResumeLayout(false);
        }

        private System.Windows.Forms.TabControl tabCtrl;
        private System.Windows.Forms.TabPage tabKhu, tabNV, tabLoai, tabDV, tabQD;
        private System.Windows.Forms.DataGridView dgvKhu, dgvNV, dgvLoaiTN, dgvDV, dgvQD;
        private System.Windows.Forms.Label lblKhuMa, lblKhuTen, lblNVMa, lblNVTen, lblNVVaiTro, lblNVSDT, lblLoaiMa, lblLoaiTen, lblDVMa, lblDVTen, lblDVDVT, lblDVGia, lblQDMa, lblQDLoai, lblQDMucDo, lblQDTien;
        private System.Windows.Forms.TextBox txtKhuMa, txtKhuTen, txtNVMa, txtNVTen, txtNVVaiTro, txtNVSDT, txtLoaiMa, txtLoaiTen, txtDVMa, txtDVTen, txtDVDVT, txtQDMa, txtQDMucDo;
        private System.Windows.Forms.NumericUpDown numDVGia, numQDTien;
        private System.Windows.Forms.ComboBox cboQDLoai;
        private System.Windows.Forms.Button btnThemKhu, btnThemNV, btnThemLoaiTN, btnThemDV, btnThemQD;
    }
}