namespace QuanLyKhachSan.Forms
{
    partial class FrmDatPhong
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.tabCtrl = new System.Windows.Forms.TabControl();
            this.tabDat = new System.Windows.Forms.TabPage();
            this.lblSoP = new System.Windows.Forms.Label();
            this.txtSoPhieu = new System.Windows.Forms.TextBox();
            this.lblKhach = new System.Windows.Forms.Label();
            this.cboKhach = new System.Windows.Forms.ComboBox();
            this.lblKenh = new System.Windows.Forms.Label();
            this.cboKenh = new System.Windows.Forms.ComboBox();
            this.lblCoc = new System.Windows.Forms.Label();
            this.numCoc = new System.Windows.Forms.NumericUpDown();
            this.dgvPhong = new System.Windows.Forms.DataGridView();
            this.dgvChon = new System.Windows.Forms.DataGridView();
            this.btnThemPhong = new System.Windows.Forms.Button();
            this.btnBoPhong = new System.Windows.Forms.Button();
            this.numSoNguoi = new System.Windows.Forms.NumericUpDown();
            this.lblSoNguoi = new System.Windows.Forms.Label();
            this.btnLapPhieu = new System.Windows.Forms.Button();
            this.lblPhieuDat = new System.Windows.Forms.Label();
            this.dgvPhieu = new System.Windows.Forms.DataGridView();
            this.tabKH = new System.Windows.Forms.TabPage();
            this.dgvKhach = new System.Windows.Forms.DataGridView();
            this.btnThemKhach = new System.Windows.Forms.Button();
            this.txtSDT = new System.Windows.Forms.TextBox();
            this.txtQT = new System.Windows.Forms.TextBox();
            this.txtCMND = new System.Windows.Forms.TextBox();
            this.txtTenKH = new System.Windows.Forms.TextBox();
            this.txtMaKH = new System.Windows.Forms.TextBox();
            this.tabNhan = new System.Windows.Forms.TabPage();
            this.btnNoShow = new System.Windows.Forms.Button();
            this.btnNhanPhong = new System.Windows.Forms.Button();
            this.txtPhieuChon = new System.Windows.Forms.TextBox();
            this.dgvCT = new System.Windows.Forms.DataGridView();
            this.dgvNguoi = new System.Windows.Forms.DataGridView();
            this.btnThemNguoi = new System.Windows.Forms.Button();
            this.txtNguoiQT = new System.Windows.Forms.TextBox();
            this.txtNguoiCMND = new System.Windows.Forms.TextBox();
            this.txtNguoiTen = new System.Windows.Forms.TextBox();
            this.txtNguoiPhong = new System.Windows.Forms.TextBox();
            this.cboNV = new System.Windows.Forms.ComboBox();
            this.dtLap = new System.Windows.Forms.DateTimePicker();
            this.dtNhan = new System.Windows.Forms.DateTimePicker();
            this.dtTra = new System.Windows.Forms.DateTimePicker();
            this.tabCtrl.SuspendLayout();
            this.tabDat.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numCoc)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvChon)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSoNguoi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhieu)).BeginInit();
            this.tabKH.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhach)).BeginInit();
            this.tabNhan.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCT)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNguoi)).BeginInit();
            this.SuspendLayout();
            // tabCtrl
            this.tabCtrl.Controls.Add(this.tabDat);
            this.tabCtrl.Controls.Add(this.tabKH);
            this.tabCtrl.Controls.Add(this.tabNhan);
            this.tabCtrl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabCtrl.Location = new System.Drawing.Point(0, 0);
            this.tabCtrl.Name = "tabCtrl";
            this.tabCtrl.Size = new System.Drawing.Size(784, 521);
            // Tab Đặt phòng (Y hệt Hình 4 của bài Lab)
            this.tabDat.Controls.Add(this.dgvPhieu);
            this.tabDat.Controls.Add(this.lblPhieuDat);
            this.tabDat.Controls.Add(this.btnLapPhieu);
            this.tabDat.Controls.Add(this.lblSoNguoi);
            this.tabDat.Controls.Add(this.numSoNguoi);
            this.tabDat.Controls.Add(this.btnBoPhong);
            this.tabDat.Controls.Add(this.btnThemPhong);
            this.tabDat.Controls.Add(this.dgvChon);
            this.tabDat.Controls.Add(this.dgvPhong);
            this.tabDat.Controls.Add(this.numCoc);
            this.tabDat.Controls.Add(this.lblCoc);
            this.tabDat.Controls.Add(this.cboKenh);
            this.tabDat.Controls.Add(this.lblKenh);
            this.tabDat.Controls.Add(this.cboKhach);
            this.tabDat.Controls.Add(this.lblKhach);
            this.tabDat.Controls.Add(this.txtSoPhieu);
            this.tabDat.Controls.Add(this.lblSoP);
            this.tabDat.Text = "Đặt phòng";
            // Hàng trên
            this.lblSoP.Location = new System.Drawing.Point(10, 15);
            this.lblSoP.Size = new System.Drawing.Size(80, 20);
            this.lblSoP.Text = "Số phiếu đặt:";
            this.txtSoPhieu.Location = new System.Drawing.Point(95, 12);
            this.txtSoPhieu.Size = new System.Drawing.Size(80, 22);
            this.lblKhach.Location = new System.Drawing.Point(185, 15);
            this.lblKhach.Size = new System.Drawing.Size(45, 20);
            this.lblKhach.Text = "Khách:";
            this.cboKhach.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboKhach.Location = new System.Drawing.Point(235, 12);
            this.cboKhach.Size = new System.Drawing.Size(130, 24);
            this.lblKenh.Location = new System.Drawing.Point(375, 15);
            this.lblKenh.Size = new System.Drawing.Size(60, 20);
            this.lblKenh.Text = "Kênh đặt:";
            this.cboKenh.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboKenh.Location = new System.Drawing.Point(440, 12);
            this.cboKenh.Size = new System.Drawing.Size(95, 24);
            this.lblCoc.Location = new System.Drawing.Point(545, 15);
            this.lblCoc.Size = new System.Drawing.Size(60, 20);
            this.lblCoc.Text = "Tiền cọc:";
            this.numCoc.Location = new System.Drawing.Point(610, 12);
            this.numCoc.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numCoc.Size = new System.Drawing.Size(100, 22);
            // 2 Lưới ở giữa
            this.dgvPhong.Location = new System.Drawing.Point(10, 48);
            this.dgvPhong.Size = new System.Drawing.Size(330, 155);
            this.lblSoNguoi.Location = new System.Drawing.Point(345, 60);
            this.lblSoNguoi.Size = new System.Drawing.Size(60, 18);
            this.lblSoNguoi.Text = "Số người:";
            this.numSoNguoi.Location = new System.Drawing.Point(348, 80);
            this.numSoNguoi.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numSoNguoi.Size = new System.Drawing.Size(55, 22);
            this.numSoNguoi.Value = new decimal(new int[] { 2, 0, 0, 0 });
            this.btnThemPhong.Location = new System.Drawing.Point(348, 110);
            this.btnThemPhong.Size = new System.Drawing.Size(55, 30);
            this.btnThemPhong.Text = ">>";
            this.btnThemPhong.Click += new System.EventHandler(this.btnThemPhong_Click);
            this.btnBoPhong.Location = new System.Drawing.Point(348, 145);
            this.btnBoPhong.Size = new System.Drawing.Size(55, 30);
            this.btnBoPhong.Text = "<<";
            this.btnBoPhong.Click += new System.EventHandler(this.btnBoPhong_Click);
            this.dgvChon.Location = new System.Drawing.Point(410, 48);
            this.dgvChon.Size = new System.Drawing.Size(350, 155);
            this.btnLapPhieu.Location = new System.Drawing.Point(630, 210);
            this.btnLapPhieu.Size = new System.Drawing.Size(130, 32);
            this.btnLapPhieu.Text = "Lập phiếu đặt";
            this.btnLapPhieu.Click += new System.EventHandler(this.btnLapPhieu_Click);
            // Lưới Phiếu đặt phòng ở dưới
            this.lblPhieuDat.Location = new System.Drawing.Point(10, 225);
            this.lblPhieuDat.Size = new System.Drawing.Size(120, 20);
            this.lblPhieuDat.Text = "Phiếu đặt phòng:";
            this.lblPhieuDat.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.dgvPhieu.Location = new System.Drawing.Point(10, 250);
            this.dgvPhieu.Size = new System.Drawing.Size(750, 215);
            this.dgvPhieu.SelectionChanged += new System.EventHandler(this.dgvPhieu_SelectionChanged);
            // Tab Khach Hang
            this.tabKH.Controls.Add(this.dgvKhach);
            this.tabKH.Controls.Add(this.btnThemKhach);
            this.tabKH.Controls.Add(this.txtSDT);
            this.tabKH.Controls.Add(this.txtQT);
            this.tabKH.Controls.Add(this.txtCMND);
            this.tabKH.Controls.Add(this.txtTenKH);
            this.tabKH.Controls.Add(this.txtMaKH);
            this.tabKH.Text = "Khách hàng";
            this.txtMaKH.Location = new System.Drawing.Point(15, 15);
            this.txtMaKH.Size = new System.Drawing.Size(80, 22);
            this.txtTenKH.Location = new System.Drawing.Point(105, 15);
            this.txtTenKH.Size = new System.Drawing.Size(150, 22);
            this.txtCMND.Location = new System.Drawing.Point(265, 15);
            this.txtCMND.Size = new System.Drawing.Size(110, 22);
            this.txtQT.Location = new System.Drawing.Point(385, 15);
            this.txtQT.Size = new System.Drawing.Size(100, 22);
            this.txtQT.Text = "Việt Nam";
            this.txtSDT.Location = new System.Drawing.Point(495, 15);
            this.txtSDT.Size = new System.Drawing.Size(110, 22);
            this.btnThemKhach.Location = new System.Drawing.Point(620, 12);
            this.btnThemKhach.Size = new System.Drawing.Size(120, 28);
            this.btnThemKhach.Text = "Thêm Khách";
            this.btnThemKhach.Click += new System.EventHandler(this.btnThemKhach_Click);
            this.dgvKhach.Location = new System.Drawing.Point(15, 55);
            this.dgvKhach.Size = new System.Drawing.Size(745, 410);
            // Tab Nhan Phong
            this.tabNhan.Controls.Add(this.btnNoShow);
            this.tabNhan.Controls.Add(this.btnNhanPhong);
            this.tabNhan.Controls.Add(this.txtPhieuChon);
            this.tabNhan.Controls.Add(this.dgvCT);
            this.tabNhan.Controls.Add(this.dgvNguoi);
            this.tabNhan.Controls.Add(this.btnThemNguoi);
            this.tabNhan.Controls.Add(this.txtNguoiQT);
            this.tabNhan.Controls.Add(this.txtNguoiCMND);
            this.tabNhan.Controls.Add(this.txtNguoiTen);
            this.tabNhan.Controls.Add(this.txtNguoiPhong);
            this.tabNhan.Text = "Nhận phòng / Người lưu trú";
            this.txtPhieuChon.Location = new System.Drawing.Point(15, 15);
            this.txtPhieuChon.ReadOnly = true;
            this.txtPhieuChon.Size = new System.Drawing.Size(120, 22);
            this.btnNhanPhong.Location = new System.Drawing.Point(145, 12);
            this.btnNhanPhong.Size = new System.Drawing.Size(110, 28);
            this.btnNhanPhong.Text = "Nhận phòng";
            this.btnNhanPhong.Click += new System.EventHandler(this.btnNhanPhong_Click);
            this.btnNoShow.Location = new System.Drawing.Point(265, 12);
            this.btnNoShow.Size = new System.Drawing.Size(110, 28);
            this.btnNoShow.Text = "No-Show";
            this.btnNoShow.Click += new System.EventHandler(this.btnNoShow_Click);
            this.dgvCT.Location = new System.Drawing.Point(15, 50);
            this.dgvCT.Size = new System.Drawing.Size(360, 360);
            this.dgvNguoi.Location = new System.Drawing.Point(390, 50);
            this.dgvNguoi.Size = new System.Drawing.Size(370, 360);
            this.txtNguoiPhong.Location = new System.Drawing.Point(15, 430);
            this.txtNguoiPhong.Size = new System.Drawing.Size(80, 22);
            this.txtNguoiTen.Location = new System.Drawing.Point(105, 430);
            this.txtNguoiTen.Size = new System.Drawing.Size(140, 22);
            this.txtNguoiCMND.Location = new System.Drawing.Point(255, 430);
            this.txtNguoiCMND.Size = new System.Drawing.Size(100, 22);
            this.txtNguoiQT.Location = new System.Drawing.Point(365, 430);
            this.txtNguoiQT.Size = new System.Drawing.Size(100, 22);
            this.txtNguoiQT.Text = "Việt Nam";
            this.btnThemNguoi.Location = new System.Drawing.Point(480, 427);
            this.btnThemNguoi.Size = new System.Drawing.Size(130, 28);
            this.btnThemNguoi.Text = "Thêm người lưu trú";
            this.btnThemNguoi.Click += new System.EventHandler(this.btnThemNguoi_Click);
            // Ẩn các control hỗ trợ
            this.cboNV.Visible = false;
            this.dtLap.Visible = false;
            this.dtNhan.Visible = false;
            this.dtTra.Visible = false;
            // FrmDatPhong
            this.ClientSize = new System.Drawing.Size(784, 521);
            this.Controls.Add(this.tabCtrl);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Khách hàng - Đặt phòng - Nhận phòng";
            this.Load += new System.EventHandler(this.FrmDatPhong_Load);
            this.tabCtrl.ResumeLayout(false);
            this.tabDat.ResumeLayout(false);
            this.tabDat.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numCoc)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvChon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSoNguoi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhieu)).EndInit();
            this.tabKH.ResumeLayout(false);
            this.tabKH.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhach)).EndInit();
            this.tabNhan.ResumeLayout(false);
            this.tabNhan.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCT)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNguoi)).EndInit();
            this.ResumeLayout(false);
        }

        private System.Windows.Forms.TabControl tabCtrl;
        private System.Windows.Forms.TabPage tabDat, tabKH, tabNhan;
        private System.Windows.Forms.Label lblSoP, lblKhach, lblKenh, lblCoc, lblSoNguoi, lblPhieuDat;
        private System.Windows.Forms.TextBox txtSoPhieu, txtPhieuChon;
        private System.Windows.Forms.ComboBox cboKhach, cboKenh, cboNV;
        private System.Windows.Forms.NumericUpDown numCoc, numSoNguoi;
        private System.Windows.Forms.DataGridView dgvPhong, dgvChon, dgvPhieu, dgvKhach, dgvCT, dgvNguoi;
        private System.Windows.Forms.Button btnThemPhong, btnBoPhong, btnLapPhieu, btnThemKhach, btnNhanPhong, btnNoShow, btnThemNguoi;
        private System.Windows.Forms.TextBox txtMaKH, txtTenKH, txtCMND, txtQT, txtSDT, txtNguoiPhong, txtNguoiTen, txtNguoiCMND, txtNguoiQT;
        private System.Windows.Forms.DateTimePicker dtLap, dtNhan, dtTra;
    }
}