CREATE DATABASE E_SHOPPING;
GO

USE E_SHOPPING;
GO

-- 1. Bảng khách hàng
CREATE TABLE KHACH_HANG (
    MaKH INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    SoDienThoai VARCHAR(15),
    DiaChi NVARCHAR(255)
);
GO

-- 2. Bảng nhóm sản phẩm
CREATE TABLE NHOM_SAN_PHAM (
    MaNhom INT IDENTITY(1,1) PRIMARY KEY,
    TenNhom NVARCHAR(100) NOT NULL
);
GO

-- 3. Bảng sản phẩm
CREATE TABLE SAN_PHAM (
    MaSP INT IDENTITY(1,1) PRIMARY KEY,
    MaNhom INT NOT NULL,
    TenSP NVARCHAR(200) NOT NULL,
    MaSanPham VARCHAR(50) NOT NULL UNIQUE,
    NhaSanXuat NVARCHAR(100),
    HinhAnh VARCHAR(255),
    MoTa NVARCHAR(MAX),
    ThongSo NVARCHAR(MAX),
    Gia DECIMAL(18,2) NOT NULL,
    TrangThaiTonKho NVARCHAR(50),

    CONSTRAINT FK_SANPHAM_NHOM
        FOREIGN KEY (MaNhom)
        REFERENCES NHOM_SAN_PHAM(MaNhom)
);
GO

-- 4. Bảng giỏ hàng
CREATE TABLE GIO_HANG (
    MaGioHang INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE(),

    CONSTRAINT FK_GIOHANG_KHACHHANG
        FOREIGN KEY (MaKH)
        REFERENCES KHACH_HANG(MaKH)
);
GO

-- 5. Chi tiết giỏ hàng
CREATE TABLE CHI_TIET_GIO_HANG (
    MaGioHang INT NOT NULL,
    MaSP INT NOT NULL,
    SoLuong INT NOT NULL,

    PRIMARY KEY (MaGioHang, MaSP),

    CONSTRAINT FK_CT_GIOHANG
        FOREIGN KEY (MaGioHang)
        REFERENCES GIO_HANG(MaGioHang),

    CONSTRAINT FK_CT_GIOHANG_SANPHAM
        FOREIGN KEY (MaSP)
        REFERENCES SAN_PHAM(MaSP)
);
GO

-- 6. Bảng đơn hàng
CREATE TABLE DON_HANG (
    MaDH INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT NOT NULL,
    HoTenNguoiNhan NVARCHAR(100) NOT NULL,
    DiaChiNhan NVARCHAR(255) NOT NULL,
    SoDienThoaiNhan VARCHAR(15) NOT NULL,
    PhuongThucGiao NVARCHAR(50) NOT NULL,
    PhiVanChuyen DECIMAL(18,2) DEFAULT 0,
    TongTien DECIMAL(18,2) NOT NULL,
    NgayDat DATETIME DEFAULT GETDATE(),

    CONSTRAINT FK_DONHANG_KHACHHANG
        FOREIGN KEY (MaKH)
        REFERENCES KHACH_HANG(MaKH)
);
GO

-- 7. Chi tiết đơn hàng
CREATE TABLE CHI_TIET_DON_HANG (
    MaDH INT NOT NULL,
    MaSP INT NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,

    PRIMARY KEY (MaDH, MaSP),

    CONSTRAINT FK_CT_DONHANG
        FOREIGN KEY (MaDH)
        REFERENCES DON_HANG(MaDH),

    CONSTRAINT FK_CT_DONHANG_SANPHAM
        FOREIGN KEY (MaSP)
        REFERENCES SAN_PHAM(MaSP)
);
GO

-- 8. Bảng thanh toán
CREATE TABLE THANH_TOAN (
    MaTT INT IDENTITY(1,1) PRIMARY KEY,
    MaDH INT NOT NULL,
    LoaiThe VARCHAR(30),
    SoThe VARCHAR(30),
    NgayHetHan DATE,
    TenChuThe NVARCHAR(100),
    CVV VARCHAR(10),
    TrangThai NVARCHAR(50),

    CONSTRAINT FK_THANHTOAN_DONHANG
        FOREIGN KEY (MaDH)
        REFERENCES DON_HANG(MaDH)
);
GO