-- 1. Tạo Database
CREATE DATABASE QuanLyTourDuLich;
GO

USE QuanLyTourDuLich;
GO

-- 2. Tạo bảng TOUR
CREATE TABLE TOUR (
    MaTour VARCHAR(20) PRIMARY KEY,
    TenTour NVARCHAR(200) NOT NULL,
    GiaTour DECIMAL(18,2) NOT NULL,
    SoNgay INT NOT NULL
);

-- 3. Tạo bảng CHUYEN_DI
CREATE TABLE CHUYEN_DI (
    MaChuyen VARCHAR(20) PRIMARY KEY,
    MaTour VARCHAR(20) FOREIGN KEY REFERENCES TOUR(MaTour),
    NgayKhoiHanh DATETIME NOT NULL,
    SoChoConLai INT NOT NULL
);

-- 4. Tạo bảng NHAN_VIEN
CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR(20) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    ChucVu NVARCHAR(50),
    LuongCoBan DECIMAL(18,2)
);

-- 5. Tạo bảng PHAN_CONG
CREATE TABLE PHAN_CONG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MaNV VARCHAR(20) FOREIGN KEY REFERENCES NHAN_VIEN(MaNV),
    MaChuyen VARCHAR(20) FOREIGN KEY REFERENCES CHUYEN_DI(MaChuyen),
    PhuCapTour DECIMAL(18,2),
    NgayBatDau DATETIME,
    NgayKetThuc DATETIME
);

-- 6. Tạo bảng PHIEU_DANG_KY_DOAN
CREATE TABLE PHIEU_DANG_KY_DOAN (
    MaPhieu VARCHAR(20) PRIMARY KEY,
    TenDoan NVARCHAR(200) NOT NULL,
    MaTour VARCHAR(20) FOREIGN KEY REFERENCES TOUR(MaTour),
    SoNguoi INT,
    NguoiDaiDien NVARCHAR(100),
    SDTLienHe VARCHAR(20),
    DiaChi NVARCHAR(200),
    TrangThai NVARCHAR(50)
);

-- 7. Tạo bảng VE_KHACH_LE
CREATE TABLE VE_KHACH_LE (
    MaVe VARCHAR(20) PRIMARY KEY,
    MaChuyen VARCHAR(20) FOREIGN KEY REFERENCES CHUYEN_DI(MaChuyen),
    TenKhach NVARCHAR(100),
    SDT VARCHAR(20),
    GiaVe DECIMAL(18,2),
    NgayDat DATETIME
);

-- 8. Tạo bảng DANH_SACH_BAO_HIEM
CREATE TABLE DANH_SACH_BAO_HIEM (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MaPhieu VARCHAR(20) FOREIGN KEY REFERENCES PHIEU_DANG_KY_DOAN(MaPhieu),
    HoTen NVARCHAR(100),
    CCCD VARCHAR(20),
    NgaySinh DATETIME
);

-- 9. Thêm Dữ liệu mẫu ban đầu
INSERT INTO TOUR VALUES 
('TOUR01', N'Tour Đà Lạt - Thành Phố Ngàn Hoa', 2500000, 3),
('TOUR02', N'Tour Phú Quốc - Thiên Đường Biển Đảo', 4500000, 4);

INSERT INTO CHUYEN_DI VALUES 
('CD01', 'TOUR01', GETDATE(), 35),
('CD02', 'TOUR02', GETDATE(), 40);

INSERT INTO NHAN_VIEN VALUES 
('NV01', N'Nguyễn Văn A', N'Hướng Dẫn Viên', 8000000),
('NV02', N'Lê Thị B', N'Hướng Dẫn Viên', 8500000);